# Generated by Django 3.2.3 on 2021-06-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('theme', models.CharField(blank=True, choices=[('Python', 'Python'), ('Django', 'Django'), ('Flask', 'Flask'), ('FastAPI', 'FastAPI'), ('Algorithms', 'Algorithms'), ('Other', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
    ]
