# Generated by Django 3.2.3 on 2021-05-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='work_status',
            field=models.BooleanField(default=False),
        ),
    ]
