# Generated by Django 3.2.3 on 2021-05-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_user_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
